services:
  # rolandomesa-ng-app:
  #   build: rolandomesa-ng
  #   ports:
  #   - 4201:4200
  rolamdomesa-netcore-api:
    build:
      context: ./RolandoMesaGdpApi
      dockerfile: ./RolandoMesaGdpApi/Dockerfile
    image: rolandomesagdp-api:latest
    ports:
    - 32771:8080